### ISSUE TITLE
Any technical reason why this is abandoned?

### ISSUE THREAD

**Issue by xekoukou** [alexcrichton/green-rs#6]
At least the libuv binding would be very useful. Why was it abandoned?

**Comment by alexcrichton** [comment]
Not particularly, it was largely just becoming too much of a burden to update through the changes of Rust a long time ago.

That being said though this library is indeed not safe today due to the stable TLS API of the standard library. Thread-local-storage is possible to access concurrently with green threading, so that may be a technical reason unfortunately.
